### ISSUE TITLE
ToDo (12/19 week 12)

### ISSUE THREAD

**Issue by jennydaman** [twlinux/unsafe#1]
- [x] tips for UNIX
  - `.` and `..`
  - `/etc/password` and `/etc/shadow`
  - `telnet` (and server hardening)
- [x] 3 reasons why you should always update software
- [x] the concept of (url) encoding
- [x] create archive of source code

- [x] Server services
  - dnsmasq
  - sshd
  - telnetd
  - vsftpd
